declare global {
    var al: any;
    var ah: any;
    var ax: unknown;
    var si: unknown;
    var cl: unknown;
    var cx: unknown;
    var bx: unknown;
    var bl: unknown;
    var bh: unknown;
    var dx: unknown;
    var dl: unknown;
    var dh: unknown;
    var sp: unknown;
    var ch: number;
    var di: unknown;
    var es: unknown;
    var cs: unknown;
    var ds: unknown;
    var ss: unknown;
    var $: number;
    var mov: (a, b) => void;
    var cmp: (a, b) => void;
    var inc: (b) => void;
    var jnz: (b) => void;
    var lodsb: () => number;
    var stosw: () => number;
    var stosb: () => number;
    var cli: () => void;
    var cld: () => void;
    var sti: () => void;
    var push: (a) => void;
    var pop: (a) => void;
    var jmp: (a) => void;
    var dec: (a) => void;
    var rol: (a, b) => void;
    var jnc: (a) => void;
    var loop: (a) => void;
    var call: (a) => void;
    var test: (a, b) => 0;
    var ret: (a?) => 0;
    var cwd: () => {};
    var div: (a) => 0;
    var mul: (a) => 0;
    var lodsw: () => 0;
    var int: (a) => 0;
}
